/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as PageRouteImport } from './routes/_page'
import { Route as PanelIndexRouteImport } from './routes/_panel.index'
import { Route as PanelUploadRouteImport } from './routes/_panel.upload'
import { Route as PanelMeRouteImport } from './routes/_panel.me'
import { Route as PanelGalleryRouteImport } from './routes/_panel.gallery'
import { Route as PanelCartRouteImport } from './routes/_panel.cart'
import { Route as PanelSpotIdRouteImport } from './routes/_panel.$spotId'
import { Route as PageOrderSuccessRouteImport } from './routes/_page.order-success'
import { Route as PageAdminRouteImport } from './routes/_page.admin'
import { Route as PanelMeIndexRouteImport } from './routes/_panel.me.index'
import { Route as PanelSpotIdIndexRouteImport } from './routes/_panel.$spotId.index'
import { Route as PanelMeEarningsRouteImport } from './routes/_panel.me.earnings'
import { Route as PanelMeCollectionsRouteImport } from './routes/_panel.me.collections'
import { Route as PanelSpotIdGalleryRouteImport } from './routes/_panel.$spotId.gallery'
import { Route as PanelMeCollectionsIndexRouteImport } from './routes/_panel.me.collections.index'
import { Route as PanelMeCollectionsPurchasesRouteImport } from './routes/_panel.me.collections.purchases'
import { Route as PanelMeCollectionsFavoritesRouteImport } from './routes/_panel.me.collections.favorites'
import { Route as PanelSpotIdSessionSessionIdRouteImport } from './routes/_panel.$spotId.session.$sessionId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/_page',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelUploadRoute = PanelUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => PanelRoute,
} as any)
const PanelMeRoute = PanelMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => PanelRoute,
} as any)
const PanelGalleryRoute = PanelGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCartRoute = PanelCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSpotIdRoute = PanelSpotIdRouteImport.update({
  id: '/$spotId',
  path: '/$spotId',
  getParentRoute: () => PanelRoute,
} as any)
const PageOrderSuccessRoute = PageOrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => PageRoute,
} as any)
const PageAdminRoute = PageAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PageRoute,
} as any)
const PanelMeIndexRoute = PanelMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelMeRoute,
} as any)
const PanelSpotIdIndexRoute = PanelSpotIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelSpotIdRoute,
} as any)
const PanelMeEarningsRoute = PanelMeEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => PanelMeRoute,
} as any)
const PanelMeCollectionsRoute = PanelMeCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => PanelMeRoute,
} as any)
const PanelSpotIdGalleryRoute = PanelSpotIdGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PanelSpotIdRoute,
} as any)
const PanelMeCollectionsIndexRoute = PanelMeCollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelMeCollectionsRoute,
} as any)
const PanelMeCollectionsPurchasesRoute =
  PanelMeCollectionsPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => PanelMeCollectionsRoute,
  } as any)
const PanelMeCollectionsFavoritesRoute =
  PanelMeCollectionsFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => PanelMeCollectionsRoute,
  } as any)
const PanelSpotIdSessionSessionIdRoute =
  PanelSpotIdSessionSessionIdRouteImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => PanelSpotIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PanelIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof PageAdminRoute
  '/order-success': typeof PageOrderSuccessRoute
  '/$spotId': typeof PanelSpotIdRouteWithChildren
  '/cart': typeof PanelCartRoute
  '/gallery': typeof PanelGalleryRoute
  '/me': typeof PanelMeRouteWithChildren
  '/upload': typeof PanelUploadRoute
  '/$spotId/gallery': typeof PanelSpotIdGalleryRoute
  '/me/collections': typeof PanelMeCollectionsRouteWithChildren
  '/me/earnings': typeof PanelMeEarningsRoute
  '/$spotId/': typeof PanelSpotIdIndexRoute
  '/me/': typeof PanelMeIndexRoute
  '/$spotId/session/$sessionId': typeof PanelSpotIdSessionSessionIdRoute
  '/me/collections/favorites': typeof PanelMeCollectionsFavoritesRoute
  '/me/collections/purchases': typeof PanelMeCollectionsPurchasesRoute
  '/me/collections/': typeof PanelMeCollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PanelIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof PageAdminRoute
  '/order-success': typeof PageOrderSuccessRoute
  '/cart': typeof PanelCartRoute
  '/gallery': typeof PanelGalleryRoute
  '/upload': typeof PanelUploadRoute
  '/$spotId/gallery': typeof PanelSpotIdGalleryRoute
  '/me/earnings': typeof PanelMeEarningsRoute
  '/$spotId': typeof PanelSpotIdIndexRoute
  '/me': typeof PanelMeIndexRoute
  '/$spotId/session/$sessionId': typeof PanelSpotIdSessionSessionIdRoute
  '/me/collections/favorites': typeof PanelMeCollectionsFavoritesRoute
  '/me/collections/purchases': typeof PanelMeCollectionsPurchasesRoute
  '/me/collections': typeof PanelMeCollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_page': typeof PageRouteWithChildren
  '/_panel': typeof PanelRouteWithChildren
  '/auth': typeof AuthRoute
  '/_page/admin': typeof PageAdminRoute
  '/_page/order-success': typeof PageOrderSuccessRoute
  '/_panel/$spotId': typeof PanelSpotIdRouteWithChildren
  '/_panel/cart': typeof PanelCartRoute
  '/_panel/gallery': typeof PanelGalleryRoute
  '/_panel/me': typeof PanelMeRouteWithChildren
  '/_panel/upload': typeof PanelUploadRoute
  '/_panel/': typeof PanelIndexRoute
  '/_panel/$spotId/gallery': typeof PanelSpotIdGalleryRoute
  '/_panel/me/collections': typeof PanelMeCollectionsRouteWithChildren
  '/_panel/me/earnings': typeof PanelMeEarningsRoute
  '/_panel/$spotId/': typeof PanelSpotIdIndexRoute
  '/_panel/me/': typeof PanelMeIndexRoute
  '/_panel/$spotId/session/$sessionId': typeof PanelSpotIdSessionSessionIdRoute
  '/_panel/me/collections/favorites': typeof PanelMeCollectionsFavoritesRoute
  '/_panel/me/collections/purchases': typeof PanelMeCollectionsPurchasesRoute
  '/_panel/me/collections/': typeof PanelMeCollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/order-success'
    | '/$spotId'
    | '/cart'
    | '/gallery'
    | '/me'
    | '/upload'
    | '/$spotId/gallery'
    | '/me/collections'
    | '/me/earnings'
    | '/$spotId/'
    | '/me/'
    | '/$spotId/session/$sessionId'
    | '/me/collections/favorites'
    | '/me/collections/purchases'
    | '/me/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/order-success'
    | '/cart'
    | '/gallery'
    | '/upload'
    | '/$spotId/gallery'
    | '/me/earnings'
    | '/$spotId'
    | '/me'
    | '/$spotId/session/$sessionId'
    | '/me/collections/favorites'
    | '/me/collections/purchases'
    | '/me/collections'
  id:
    | '__root__'
    | '/_page'
    | '/_panel'
    | '/auth'
    | '/_page/admin'
    | '/_page/order-success'
    | '/_panel/$spotId'
    | '/_panel/cart'
    | '/_panel/gallery'
    | '/_panel/me'
    | '/_panel/upload'
    | '/_panel/'
    | '/_panel/$spotId/gallery'
    | '/_panel/me/collections'
    | '/_panel/me/earnings'
    | '/_panel/$spotId/'
    | '/_panel/me/'
    | '/_panel/$spotId/session/$sessionId'
    | '/_panel/me/collections/favorites'
    | '/_panel/me/collections/purchases'
    | '/_panel/me/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRouteWithChildren
  PanelRoute: typeof PanelRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page': {
      id: '/_page'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/': {
      id: '/_panel/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/upload': {
      id: '/_panel/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof PanelUploadRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/me': {
      id: '/_panel/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof PanelMeRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/gallery': {
      id: '/_panel/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PanelGalleryRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/cart': {
      id: '/_panel/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof PanelCartRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/$spotId': {
      id: '/_panel/$spotId'
      path: '/$spotId'
      fullPath: '/$spotId'
      preLoaderRoute: typeof PanelSpotIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_page/order-success': {
      id: '/_page/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof PageOrderSuccessRouteImport
      parentRoute: typeof PageRoute
    }
    '/_page/admin': {
      id: '/_page/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PageAdminRouteImport
      parentRoute: typeof PageRoute
    }
    '/_panel/me/': {
      id: '/_panel/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof PanelMeIndexRouteImport
      parentRoute: typeof PanelMeRoute
    }
    '/_panel/$spotId/': {
      id: '/_panel/$spotId/'
      path: '/'
      fullPath: '/$spotId/'
      preLoaderRoute: typeof PanelSpotIdIndexRouteImport
      parentRoute: typeof PanelSpotIdRoute
    }
    '/_panel/me/earnings': {
      id: '/_panel/me/earnings'
      path: '/earnings'
      fullPath: '/me/earnings'
      preLoaderRoute: typeof PanelMeEarningsRouteImport
      parentRoute: typeof PanelMeRoute
    }
    '/_panel/me/collections': {
      id: '/_panel/me/collections'
      path: '/collections'
      fullPath: '/me/collections'
      preLoaderRoute: typeof PanelMeCollectionsRouteImport
      parentRoute: typeof PanelMeRoute
    }
    '/_panel/$spotId/gallery': {
      id: '/_panel/$spotId/gallery'
      path: '/gallery'
      fullPath: '/$spotId/gallery'
      preLoaderRoute: typeof PanelSpotIdGalleryRouteImport
      parentRoute: typeof PanelSpotIdRoute
    }
    '/_panel/me/collections/': {
      id: '/_panel/me/collections/'
      path: '/'
      fullPath: '/me/collections/'
      preLoaderRoute: typeof PanelMeCollectionsIndexRouteImport
      parentRoute: typeof PanelMeCollectionsRoute
    }
    '/_panel/me/collections/purchases': {
      id: '/_panel/me/collections/purchases'
      path: '/purchases'
      fullPath: '/me/collections/purchases'
      preLoaderRoute: typeof PanelMeCollectionsPurchasesRouteImport
      parentRoute: typeof PanelMeCollectionsRoute
    }
    '/_panel/me/collections/favorites': {
      id: '/_panel/me/collections/favorites'
      path: '/favorites'
      fullPath: '/me/collections/favorites'
      preLoaderRoute: typeof PanelMeCollectionsFavoritesRouteImport
      parentRoute: typeof PanelMeCollectionsRoute
    }
    '/_panel/$spotId/session/$sessionId': {
      id: '/_panel/$spotId/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/$spotId/session/$sessionId'
      preLoaderRoute: typeof PanelSpotIdSessionSessionIdRouteImport
      parentRoute: typeof PanelSpotIdRoute
    }
  }
}

interface PageRouteChildren {
  PageAdminRoute: typeof PageAdminRoute
  PageOrderSuccessRoute: typeof PageOrderSuccessRoute
}

const PageRouteChildren: PageRouteChildren = {
  PageAdminRoute: PageAdminRoute,
  PageOrderSuccessRoute: PageOrderSuccessRoute,
}

const PageRouteWithChildren = PageRoute._addFileChildren(PageRouteChildren)

interface PanelSpotIdRouteChildren {
  PanelSpotIdGalleryRoute: typeof PanelSpotIdGalleryRoute
  PanelSpotIdIndexRoute: typeof PanelSpotIdIndexRoute
  PanelSpotIdSessionSessionIdRoute: typeof PanelSpotIdSessionSessionIdRoute
}

const PanelSpotIdRouteChildren: PanelSpotIdRouteChildren = {
  PanelSpotIdGalleryRoute: PanelSpotIdGalleryRoute,
  PanelSpotIdIndexRoute: PanelSpotIdIndexRoute,
  PanelSpotIdSessionSessionIdRoute: PanelSpotIdSessionSessionIdRoute,
}

const PanelSpotIdRouteWithChildren = PanelSpotIdRoute._addFileChildren(
  PanelSpotIdRouteChildren,
)

interface PanelMeCollectionsRouteChildren {
  PanelMeCollectionsFavoritesRoute: typeof PanelMeCollectionsFavoritesRoute
  PanelMeCollectionsPurchasesRoute: typeof PanelMeCollectionsPurchasesRoute
  PanelMeCollectionsIndexRoute: typeof PanelMeCollectionsIndexRoute
}

const PanelMeCollectionsRouteChildren: PanelMeCollectionsRouteChildren = {
  PanelMeCollectionsFavoritesRoute: PanelMeCollectionsFavoritesRoute,
  PanelMeCollectionsPurchasesRoute: PanelMeCollectionsPurchasesRoute,
  PanelMeCollectionsIndexRoute: PanelMeCollectionsIndexRoute,
}

const PanelMeCollectionsRouteWithChildren =
  PanelMeCollectionsRoute._addFileChildren(PanelMeCollectionsRouteChildren)

interface PanelMeRouteChildren {
  PanelMeCollectionsRoute: typeof PanelMeCollectionsRouteWithChildren
  PanelMeEarningsRoute: typeof PanelMeEarningsRoute
  PanelMeIndexRoute: typeof PanelMeIndexRoute
}

const PanelMeRouteChildren: PanelMeRouteChildren = {
  PanelMeCollectionsRoute: PanelMeCollectionsRouteWithChildren,
  PanelMeEarningsRoute: PanelMeEarningsRoute,
  PanelMeIndexRoute: PanelMeIndexRoute,
}

const PanelMeRouteWithChildren =
  PanelMeRoute._addFileChildren(PanelMeRouteChildren)

interface PanelRouteChildren {
  PanelSpotIdRoute: typeof PanelSpotIdRouteWithChildren
  PanelCartRoute: typeof PanelCartRoute
  PanelGalleryRoute: typeof PanelGalleryRoute
  PanelMeRoute: typeof PanelMeRouteWithChildren
  PanelUploadRoute: typeof PanelUploadRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelSpotIdRoute: PanelSpotIdRouteWithChildren,
  PanelCartRoute: PanelCartRoute,
  PanelGalleryRoute: PanelGalleryRoute,
  PanelMeRoute: PanelMeRouteWithChildren,
  PanelUploadRoute: PanelUploadRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRouteWithChildren,
  PanelRoute: PanelRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
