/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as PageRouteImport } from './routes/_page'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelMeRouteImport } from './routes/_panel.me'
import { Route as PanelCartRouteImport } from './routes/_panel.cart'
import { Route as PanelSpotIdRouteImport } from './routes/_panel.$spotId'
import { Route as PageOrderSuccessRouteImport } from './routes/_page.order-success'
import { Route as PageAccountRouteImport } from './routes/_page.account'
import { Route as PanelMeIndexRouteImport } from './routes/_panel.me.index'
import { Route as PanelSpotIdIndexRouteImport } from './routes/_panel.$spotId.index'
import { Route as PanelMePurchasesRouteImport } from './routes/_panel.me.purchases'
import { Route as PanelMeFavoritesRouteImport } from './routes/_panel.me.favorites'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/_page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelMeRoute = PanelMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCartRoute = PanelCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSpotIdRoute = PanelSpotIdRouteImport.update({
  id: '/$spotId',
  path: '/$spotId',
  getParentRoute: () => PanelRoute,
} as any)
const PageOrderSuccessRoute = PageOrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => PageRoute,
} as any)
const PageAccountRoute = PageAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PageRoute,
} as any)
const PanelMeIndexRoute = PanelMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelMeRoute,
} as any)
const PanelSpotIdIndexRoute = PanelSpotIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelSpotIdRoute,
} as any)
const PanelMePurchasesRoute = PanelMePurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => PanelMeRoute,
} as any)
const PanelMeFavoritesRoute = PanelMeFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => PanelMeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof PageAccountRoute
  '/order-success': typeof PageOrderSuccessRoute
  '/$spotId': typeof PanelSpotIdRouteWithChildren
  '/cart': typeof PanelCartRoute
  '/me': typeof PanelMeRouteWithChildren
  '/me/favorites': typeof PanelMeFavoritesRoute
  '/me/purchases': typeof PanelMePurchasesRoute
  '/$spotId/': typeof PanelSpotIdIndexRoute
  '/me/': typeof PanelMeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof PageAccountRoute
  '/order-success': typeof PageOrderSuccessRoute
  '/cart': typeof PanelCartRoute
  '/me/favorites': typeof PanelMeFavoritesRoute
  '/me/purchases': typeof PanelMePurchasesRoute
  '/$spotId': typeof PanelSpotIdIndexRoute
  '/me': typeof PanelMeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_page': typeof PageRouteWithChildren
  '/_panel': typeof PanelRouteWithChildren
  '/auth': typeof AuthRoute
  '/_page/account': typeof PageAccountRoute
  '/_page/order-success': typeof PageOrderSuccessRoute
  '/_panel/$spotId': typeof PanelSpotIdRouteWithChildren
  '/_panel/cart': typeof PanelCartRoute
  '/_panel/me': typeof PanelMeRouteWithChildren
  '/_panel/me/favorites': typeof PanelMeFavoritesRoute
  '/_panel/me/purchases': typeof PanelMePurchasesRoute
  '/_panel/$spotId/': typeof PanelSpotIdIndexRoute
  '/_panel/me/': typeof PanelMeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/order-success'
    | '/$spotId'
    | '/cart'
    | '/me'
    | '/me/favorites'
    | '/me/purchases'
    | '/$spotId/'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/order-success'
    | '/cart'
    | '/me/favorites'
    | '/me/purchases'
    | '/$spotId'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/_page'
    | '/_panel'
    | '/auth'
    | '/_page/account'
    | '/_page/order-success'
    | '/_panel/$spotId'
    | '/_panel/cart'
    | '/_panel/me'
    | '/_panel/me/favorites'
    | '/_panel/me/purchases'
    | '/_panel/$spotId/'
    | '/_panel/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRoute: typeof PageRouteWithChildren
  PanelRoute: typeof PanelRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page': {
      id: '/_page'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/me': {
      id: '/_panel/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof PanelMeRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/cart': {
      id: '/_panel/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof PanelCartRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/$spotId': {
      id: '/_panel/$spotId'
      path: '/$spotId'
      fullPath: '/$spotId'
      preLoaderRoute: typeof PanelSpotIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_page/order-success': {
      id: '/_page/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof PageOrderSuccessRouteImport
      parentRoute: typeof PageRoute
    }
    '/_page/account': {
      id: '/_page/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof PageAccountRouteImport
      parentRoute: typeof PageRoute
    }
    '/_panel/me/': {
      id: '/_panel/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof PanelMeIndexRouteImport
      parentRoute: typeof PanelMeRoute
    }
    '/_panel/$spotId/': {
      id: '/_panel/$spotId/'
      path: '/'
      fullPath: '/$spotId/'
      preLoaderRoute: typeof PanelSpotIdIndexRouteImport
      parentRoute: typeof PanelSpotIdRoute
    }
    '/_panel/me/purchases': {
      id: '/_panel/me/purchases'
      path: '/purchases'
      fullPath: '/me/purchases'
      preLoaderRoute: typeof PanelMePurchasesRouteImport
      parentRoute: typeof PanelMeRoute
    }
    '/_panel/me/favorites': {
      id: '/_panel/me/favorites'
      path: '/favorites'
      fullPath: '/me/favorites'
      preLoaderRoute: typeof PanelMeFavoritesRouteImport
      parentRoute: typeof PanelMeRoute
    }
  }
}

interface PageRouteChildren {
  PageAccountRoute: typeof PageAccountRoute
  PageOrderSuccessRoute: typeof PageOrderSuccessRoute
}

const PageRouteChildren: PageRouteChildren = {
  PageAccountRoute: PageAccountRoute,
  PageOrderSuccessRoute: PageOrderSuccessRoute,
}

const PageRouteWithChildren = PageRoute._addFileChildren(PageRouteChildren)

interface PanelSpotIdRouteChildren {
  PanelSpotIdIndexRoute: typeof PanelSpotIdIndexRoute
}

const PanelSpotIdRouteChildren: PanelSpotIdRouteChildren = {
  PanelSpotIdIndexRoute: PanelSpotIdIndexRoute,
}

const PanelSpotIdRouteWithChildren = PanelSpotIdRoute._addFileChildren(
  PanelSpotIdRouteChildren,
)

interface PanelMeRouteChildren {
  PanelMeFavoritesRoute: typeof PanelMeFavoritesRoute
  PanelMePurchasesRoute: typeof PanelMePurchasesRoute
  PanelMeIndexRoute: typeof PanelMeIndexRoute
}

const PanelMeRouteChildren: PanelMeRouteChildren = {
  PanelMeFavoritesRoute: PanelMeFavoritesRoute,
  PanelMePurchasesRoute: PanelMePurchasesRoute,
  PanelMeIndexRoute: PanelMeIndexRoute,
}

const PanelMeRouteWithChildren =
  PanelMeRoute._addFileChildren(PanelMeRouteChildren)

interface PanelRouteChildren {
  PanelSpotIdRoute: typeof PanelSpotIdRouteWithChildren
  PanelCartRoute: typeof PanelCartRoute
  PanelMeRoute: typeof PanelMeRouteWithChildren
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelSpotIdRoute: PanelSpotIdRouteWithChildren,
  PanelCartRoute: PanelCartRoute,
  PanelMeRoute: PanelMeRouteWithChildren,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRoute: PageRouteWithChildren,
  PanelRoute: PanelRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
